<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59e49e0fe2f38',
	'title' => 'Event Participant Fields',
	'fields' => array (
		array (
			'key' => 'field_59e49e1419265',
			'label' => 'Participant Limit',
			'name' => 'participant_limit',
			'type' => 'true_false',
			'instructions' => 'Check if the participant entries should be limited.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Participant Limit',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59e5be3109d59',
			'label' => 'Max Invited Participants',
			'name' => 'max_invited_participants',
			'type' => 'number',
			'instructions' => 'Set the maximum amount of participants that will be invited. This triggers the waiting list message on the event sign-ups.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59e49e1419265',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 50,
			'prepend' => '',
			'append' => 'Participants',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_5a4229a185b64',
			'label' => 'Resumé (CV)',
			'name' => 'resume',
			'type' => 'radio',
			'instructions' => 'Choose whether a resumé is not required, optional or required.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59e49e1419265',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'No' => 'No',
				'Optional' => 'Optional',
				'Required' => 'Required',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'No',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5a422a4b85b65',
			'label' => 'Motivation',
			'name' => 'motivation',
			'type' => 'radio',
			'instructions' => 'Choose whether a motivation is not required, optional or required.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59e49e1419265',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'No' => 'No',
				'Optional' => 'Optional',
				'Required' => 'Required',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'No',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5a422a4d85b66',
			'label' => 'Portfolio',
			'name' => 'portfolio',
			'type' => 'radio',
			'instructions' => 'Choose whether a portfolio is not required, optional or required.',
			'required' => 1,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59e49e1419265',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'No' => 'No',
				'Optional' => 'Optional',
				'Required' => 'Required',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'No',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5a1181b250f6d',
			'label' => 'Participant List',
			'name' => 'participant_list',
			'type' => 'repeater',
			'instructions' => 'This is a list of the participants that signed up. You can either sign people up from here, or on an event page.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59e49e1419265',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5a1182a650f6e',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Participant',
			'sub_fields' => array (
				array (
					'key' => 'field_5a1182a650f6e',
					'label' => 'First Name',
					'name' => 'first_name',
					'type' => 'text',
					'instructions' => 'Participant\'s first name.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5a1182d050f6f',
					'label' => 'Last Name',
					'name' => 'last_name',
					'type' => 'text',
					'instructions' => 'Participant\'s last name.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5a1182e150f70',
					'label' => 'E-Mail Address',
					'name' => 'email',
					'type' => 'email',
					'instructions' => 'Participant\'s E-Mail Address.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array (
					'key' => 'field_5a11831f50f71',
					'label' => 'Phone Number',
					'name' => 'phone_number',
					'type' => 'text',
					'instructions' => 'Participant\'s phone number.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_5a11834e50f72',
					'label' => 'Resume',
					'name' => 'resume',
					'type' => 'file',
					'instructions' => 'Participant\'s resume in PDF format (smaller than 10MB).',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5a4229a185b64',
								'operator' => '!=',
								'value' => 'No',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => 10,
					'mime_types' => 'PDF',
				),
				array (
					'key' => 'field_5a1183a250f73',
					'label' => 'Motivation letter',
					'name' => 'motivation',
					'type' => 'file',
					'instructions' => 'Participant\'s motivation letter (PDF under 10MB).',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5a422a4b85b65',
								'operator' => '!=',
								'value' => 'No',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => 10,
					'mime_types' => 'PDF',
				),
				array (
					'key' => 'field_5a1183e050f74',
					'label' => 'Portfolio',
					'name' => 'portfolio',
					'type' => 'file',
					'instructions' => 'Participant\'s portfolio (PDF file under 25MB).',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5a422a4d85b66',
								'operator' => '!=',
								'value' => 'No',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => 25,
					'mime_types' => 'PDF',
				),
				array (
					'key' => 'field_5a1d7c37cfcc0',
					'label' => 'Unique ID',
					'name' => 'unique_ID',
					'type' => 'text',
					'instructions' => 'Unique ID used for deleting an event sign-up (do not edit!)',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_5a422ed6eb3c7',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '0',
						'class' => '',
						'id' => '',
					),
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_5a422ed6eb3c7',
			'label' => 'Show unique ID field',
			'name' => 'show_unique_id_field',
			'type' => 'true_false',
			'instructions' => 'Shouldn\'t be necessary. Developer function!',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59e49e1419265',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
